name: 'Check PR'

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies 📦
        run: npm install --ignore-scripts

      - name: Run build 🧪
        run: npm run build

      - name: Run linter 👀
        run: npm run lint

      - name: Run tests 🧪
        run: npm run test
